### ISSUE TITLE
Link to the community on github page

### ISSUE THREAD

**Issue by wiki-me** [freamon/lemmy-trending-communities-bot#2]
There is an [open pull request](https://github.com/dbeley/awesome-lemmy/pull/14) that is not merged in awesome lemmy (A curated list of lemmy resources). Maybe it will be accepted if the link will be to github.

I am talking about the section under short description, in [lemmy repository](https://github.com/LemmyNet/lemmy) it's the section under "A link aggregator and forum for the fediverse" above the github topics ("chat" "rust" and "reddit").

**Comment by freamon** [comment]
It's maybe a loose fit for that repo. A link to the Community is probably more appropriate than a link to the GitHub, but it would need to be an absolute link: https://feddit.nl/c/trendingcommunities. The one in your PR is one that is relative to lemmy.ml.

If you change your PR and still have no luck, I'll try with a GitHub link.

**Comment by wiki-me** [comment]
I improved the submission like you said, and added a link manually (which i think should work), i still think it is a good idea to have a link to the community, one of the advantages of github is that it supports discovering repositories, someone might come across your repo and might have a hard time understanding whats it's about.

**Comment by freamon** [comment]
The PR looks better now, if they don't want to include it, I hope they say why.

I've added links to the Lemmy sites in the README for this repo (it was a daft thing for me not to do before)

**Comment by wiki-me** [comment]
I still think it is good to change the link, people tend to have certain "scan patterns" when reviewing a page, if it's in the read me it is easier to miss.

![Screenshot_20230815_084758](https://github.com/freamon/lemmy-trending-communities-bot/assets/68199012/c6f912a2-5bde-4889-a7f2-67d357d50662)

You basically press the button i marked and update "website".

**Comment by freamon** [comment]
Thanks. Sorry for needing step-by-step instructions to such a basic thing (I don't use GitHub much). I've updated it now.

**Comment by freamon** [comment]
Closing now, as PR is merged (!), and I think I've followed the good suggestions for this repo.
